### ISSUE TITLE
CH Maps Swisstopo are now free to use

### ISSUE THREAD

**Issue by pramach** [tumic0/GPXSee-maps#50]
Hi

Since march 1, 2021 the Swisstopo maps are now free to use.
Details in english see: https://www.swisstopo.admin.ch/en/geodata/geoservices/bgdi-services.html

The map access is available via WMS-IFDG, WMTS-IFDG and Vector Tiles Service-IFDG.

I try to change the existing ppl to xml and adapt to the WMS and WMTS path but failed due to missing Set or Default ....

As I do not know what the allowed values are, may I ask you to adapt the SwissTopo map settings accordingly ?

Thx
Wolfgang

**Comment by tumic0** [comment]
I have added the "new" Swisstopo maps in a31c18a90f9cd18fbc45ca42f20f0e42e74af990. However, they will only work with the current GPXsee HEAD (and later with GPXSee 8.9 and newer) due to Swisstopo using yet another non-standard CRS urn format.

(The files will be added to the catalogue - gh-pages - when GPXSee 8.9 is released)

**Comment by pramach** [comment]
Hi
Just noticed that the files are still as TPL.
May I ask you to release them now as GPXSee 8.9 is out ;-)
Thanks a lot
Wolfgang

**Comment by pramach** [comment]
Btw, I used the map definitions in your a31c18a link above and it works well.
Again many thanks.

**Comment by tumic0** [comment]
The online catalogue is up-to-date now. There is additionally a Landeskarte 1:25000 map, which has better details on some zoom levels.

**Comment by pramach** [comment]
Thanks again a lot
